# Generated by Django 5.2 on 2025-04-13 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0013_remove_device_device_id_remove_device_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_number', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('handover_datetime', models.DateTimeField(blank=True, null=True)),
                ('takeover_datetime', models.DateTimeField(blank=True, null=True)),
                ('device_status', models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('in_repair', 'In Repair'), ('retired', 'Retired')], default='working', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_transactions', to='login.device')),
                ('handover_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_handovers_given', to=settings.AUTH_USER_MODEL)),
                ('takeover_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_takeovers_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Transaction',
                'verbose_name_plural': 'Device Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
