# Generated by Django 5.2 on 2025-04-10 22:15

import login.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_customuser_state'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', login.models.CustomUserManager()),
            ],
        ),
    ]
