# Generated by Django 5.2 on 2025-04-11 22:12

from django.db import migrations, models

def set_default_make(apps, schema_editor):
    Device = apps.get_model('login', 'Device')
    Device.objects.all().update(make='Other')

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_enable_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='make',
            field=models.CharField(choices=[('Zebra', 'Zebra'), ('Honeywell', 'Honeywell'), ('Urovo', 'Urovo'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged')], default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(default='Barcode Scanner', max_length=50),
        ),
        migrations.RunPython(set_default_make),
    ]
