# Generated by Django 5.2 on 2025-04-11 22:24

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

def set_default_department(apps, schema_editor):
    Device = apps.get_model('login', 'Device')
    Device.objects.all().update(department='IT')

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20250411_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.CharField(default='IT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='damage_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='damage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_department),
    ]
