# Generated by Django 5.2 on 2025-04-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20250411_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='purchase_date',
        ),
    ]
