# Generated by Django 4.2.7 on 2025-04-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_device_device_id_remove_device_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='status',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='damage_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='damage_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='handovertakeover',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='handovertakeover',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='handovertakeover',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='handovertakeover',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='handovertakeover',
            name='notes',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('stock', 'Stock'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance')], default='stock', max_length=20),
        ),
        migrations.AddField(
            model_name='handovertakeover',
            name='device_condition',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged')], default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handovertakeover',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handovertakeover',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handovertakeover',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handovertakeover',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='handovertakeover',
            name='transaction_type',
            field=models.CharField(choices=[('handover', 'Handover'), ('takeover', 'Takeover')], max_length=20),
        ),
    ]
