# Generated by Django 4.2.7 on 2025-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_device_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='make',
            field=models.CharField(help_text='Enter the manufacturer/brand of the device', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(help_text='Enter the model name/number of the device', max_length=100),
        ),
    ]
