# Generated by Django 4.2.7 on 2025-04-13 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_device_make_alter_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handovertakeover',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handover_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
