# Generated by Django 4.2.7 on 2025-04-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_handovertakeover_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='damage_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='damaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
