# Generated by Django 4.2.7 on 2025-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_device_damage_datetime_device_damaged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='damage_info',
            field=models.TextField(blank=True, help_text='Information about the damage if device is damaged', null=True),
        ),
    ]
