# Generated by Django 4.2.7 on 2025-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_device_damage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='damage_info',
            field=models.TextField(blank=True, help_text='Description of the damage', null=True),
        ),
    ]
