# Generated by Django 4.2.7 on 2025-04-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_device_damage_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='damage_datetime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='damage_info',
        ),
        migrations.RemoveField(
            model_name='device',
            name='damaged_by',
        ),
    ]
