# Generated by Django 4.2.7 on 2025-04-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0014_rename_status_device_condition_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicetransaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_device_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicetransaction',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.device'),
        ),
        migrations.AlterField(
            model_name='devicetransaction',
            name='device_status',
            field=models.CharField(choices=[('stock', 'Stock'), ('assigned', 'Assigned'), ('damaged', 'Damaged'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devicetransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
