# Generated by Django 4.2.7 on 2025-04-13 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_devicetransaction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_transaction_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicetransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transaction_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
