# Generated by Django 5.2 on 2025-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_customuser_disable_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enable_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
