# Generated by Django 4.2.7 on 2025-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_rename_status_device_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='make',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('microsoft', 'Microsoft'), ('asus', 'ASUS'), ('acer', 'Acer'), ('other', 'Other')], max_length=100),
        ),
    ]
